FROM golang:1.24.4 AS builder

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app
COPY . .

RUN rm -rf .git

RUN GOARCH=wasm GOOS=js go build -gcflags="all=-N -l" -o web/app.wasm cmd/frontend/main.go 
RUN CGO_ENABLED=0 GOOSE=linux GO111MODULE=on go build -gcflags="all=-N -l" -a -installsuffix nocgo -o accounter cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates gcompat
WORKDIR /app

COPY --from=builder /app/ ./
COPY --from=builder /go/bin/dlv /dlv

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/app/accounter"]
