prod: &default
  secret_key: 48716746efd74c80b72175f17e40224f
  token_expire: 744h

  client:
    port: 8000
  http:
    port: 8001
    allow_origins:
      - http://localhost
    allow_headers:
      - Authorization
      - X-Requested-With
      - X-Client-Version
      - Origin
      - Content-Type
      - WithCredentials
    allow_methods:
      - PUT
      - PATCH
      - GET
      - POST
      - DELETE
      - OPTIONS
    allow_wildcard: true
    allow_credentials: true
    expose_headers:
      - Content-Length
      - Content-Disposition
    max_age: 12h
    websocket:
      read_deadline: 1m
      write_deadline: 3s
  db:
    driver: postgres
    dsn: user=uter password=28031988Uter host=192.168.0.107 port=5432 dbname=main
dev: 
  <<: *default