prod: &default
  secret_key: 48716746efd74c80b72175f17e40224f
  token_expire: 744h

  client:
    port: 8000
  http:
    port: 8001
    allow_origins:
      - http://localhost
    allow_headers:
      - Authorization
      - X-Requested-With
      - X-Client-Version
      - Origin
      - Content-Type
      - WithCredentials
    allow_methods:
      - PUT
      - PATCH
      - GET
      - POST
      - DELETE
      - OPTIONS
    allow_wildcard: true
    allow_credentials: true
    expose_headers:
      - Content-Length
      - Content-Disposition
    max_age: 12h
    read_timeout: 20m
    write_timeout: 20m
    websocket:
      url: ws://localhost:8001/api/v1/websocket
      read_deadline: 1m
      write_deadline: 3s
      reconnection_interval: 5s
      ping_interval: 30s
  db:
    driver: postgres
    user: uter
    password: 28031988Uter
    host: localhost
    port: 5431
    dbname: main
    ssl_mode: disable
  kafka:
    topic: events
    group: accounter
    brokers:
      - localhost:9092
    read_timeout: 10s
    write_timeout: 10s
    auto_commit: false
dev: 
  <<: *default